import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../providers/medications_provider.dart';
import '../models/medication.dart';
import 'package:kidneytrack_mobile/core/theme/app_colors.dart';
import 'package:kidneytrack_mobile/core/theme/app_text_styles.dart';
import '../../../core/utils/dialogs.dart';
import '../../../core/data/medications_database.dart';
import '../../../core/data/drug_interactions.dart';
import 'package:kidneytrack_mobile/l10n/app_localizations.dart';

class AddMedicationScreen extends ConsumerStatefulWidget {
  const AddMedicationScreen({super.key});

  @override
  ConsumerState<AddMedicationScreen> createState() =>
      _AddMedicationScreenState();
}

class _AddMedicationScreenState extends ConsumerState<AddMedicationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _doseController = TextEditingController();
  final _notesController = TextEditingController();

  Map<String, dynamic>? _selectedMedData;
  String? _interactionWarning;

  final String _frequency = 'daily';
  final List<String> _times = ['08:00', '20:00'];
  final DateTime _startDate = DateTime.now();
  DateTime? _endDate;
  bool _isSaving = false;
  bool _isDirty = false;

  void _onMedicationSelected(String name) {
    setState(() {
      _selectedMedData = knownMedications.firstWhere(
        (m) => m['name'] == name || m['nameAr'] == name,
        orElse: () => {},
      );
      if (_selectedMedData?.isEmpty ?? true) _selectedMedData = null;

      _checkInteractions(name);
      _isDirty = true;
    });
  }

  void _checkInteractions(String newMedName) {
    _interactionWarning = null;
    final currentMeds = ref.read(medicationsProvider).medications;

    for (final existingMed in currentMeds) {
      for (final interaction in drugInteractions) {
        final d1 = interaction['drug1'];
        final d2 = interaction['drug2'];

        if ((d1 == newMedName && d2 == existingMed.name) ||
            (d2 == newMedName && d1 == existingMed.name)) {
          _interactionWarning = interaction['message'];
          return;
        }
      }
    }
  }

  Future<void> _selectTime(int index) async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay(
        hour: int.parse(_times[index].split(':')[0]),
        minute: int.parse(_times[index].split(':')[1]),
      ),
    );
    if (picked != null) {
      setState(() {
        _times[index] =
            '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}';
        _isDirty = true;
      });
    }
  }

  void _addTime() {
    setState(() {
      _times.add('12:00');
      _isDirty = true;
    });
  }

  void _removeTime(int index) {
    if (_times.length > 1) {
      setState(() {
        _times.removeAt(index);
        _isDirty = true;
      });
    }
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSaving = true);
    try {
      final userId = Supabase.instance.client.auth.currentUser!.id;
      final med = Medication(
        id: '', // Will be generated by Supabase
        patientId: userId,
        name: _nameController.text,
        dose: _doseController.text,
        frequency: _frequency,
        times: _times,
        startDate: _startDate,
        endDate: _endDate,
        notes: _notesController.text,
        medicationKey: _selectedMedData?['name'],
        isNephrotoxic: _selectedMedData?['nephrotoxic'] ?? false,
        needsDoseAdjustment: _selectedMedData?['doseAdjustment'] ?? false,
        renalWarning: _selectedMedData?['warning'] ?? _interactionWarning,
      );

      await ref.read(medicationsProvider.notifier).addMedication(med);
      if (mounted) context.pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text('خطأ في الحفظ: $e'),
              backgroundColor: AppColors.textCritical),
        );
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final l10n = AppLocalizations.of(context)!;

    return PopScope(
      canPop: !_isDirty,
      onPopInvokedWithResult: (bool didPop, dynamic result) async {
        if (didPop) return;
        final shouldPop = await showExitConfirmDialog(context);
        if (shouldPop && context.mounted) context.pop();
      },
      child: FocusScope(
        child: Scaffold(
          backgroundColor: isDark ? AppColors.bgSurfaceDark : AppColors.bgBase,
          appBar: AppBar(
            title: Text(l10n.addNewMedication, style: AppTextStyles.h2),
            backgroundColor: isDark ? AppColors.bgSurfaceDark : Colors.white,
            foregroundColor: isDark ? Colors.white : Colors.black,
            elevation: 0,
            leading: IconButton(
              icon: const Icon(Icons.arrow_back_ios_new_rounded),
              onPressed: () async {
                if (!_isDirty) {
                  context.pop();
                  return;
                }
                final shouldPop = await showExitConfirmDialog(context);
                if (shouldPop && context.mounted) context.pop();
              },
            ),
          ),
          body: Form(
            key: _formKey,
            child: ListView(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
              children: [
                _buildField(
                  label: l10n.medicationName,
                  isRequired: true,
                  child: RawAutocomplete<String>(
                    optionsBuilder: (TextEditingValue textEditingValue) {
                      if (textEditingValue.text == '') {
                        return const Iterable<String>.empty();
                      }
                      return knownMedications
                          .where((Map<String, dynamic> option) {
                        return option['name'].toString().toLowerCase().contains(
                                textEditingValue.text.toLowerCase()) ||
                            option['nameAr']
                                .toString()
                                .contains(textEditingValue.text);
                      }).map((m) => '${m['name']} (${m['nameAr']})');
                    },
                    onSelected: (String selection) {
                      final name = selection.split(' (')[0];
                      _nameController.text = name;
                      _onMedicationSelected(name);
                    },
                    fieldViewBuilder:
                        (context, controller, focusNode, onFieldSubmitted) {
                      return TextFormField(
                        controller: controller,
                        focusNode: focusNode,
                        style: AppTextStyles.bodyM,
                        decoration: _buildInputDecoration(
                          context: context,
                          hint: l10n.searchMedicationHint,
                          prefixIcon: Icons.search_rounded,
                        ),
                        onChanged: (v) {
                          _nameController.text = v;
                          _onMedicationSelected(v);
                        },
                        validator: (v) => v == null || v.isEmpty
                            ? l10n.medicationNameRequired
                            : null,
                      );
                    },
                    optionsViewBuilder: (context, onSelected, options) {
                      return Align(
                        alignment: Alignment.topLeft,
                        child: Material(
                          elevation: 4.0,
                          borderRadius: BorderRadius.circular(12),
                          child: SizedBox(
                            width: MediaQuery.of(context).size.width - 48,
                            child: ListView.builder(
                              padding: EdgeInsets.zero,
                              shrinkWrap: true,
                              itemCount: options.length,
                              itemBuilder: (BuildContext context, int index) {
                                final String option = options.elementAt(index);
                                return ListTile(
                                  title:
                                      Text(option, style: AppTextStyles.bodyM),
                                  onTap: () => onSelected(option),
                                );
                              },
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                ),
                if (_selectedMedData != null ||
                    _interactionWarning != null) ...[
                  const SizedBox(height: 16),
                  _buildSafetyCard(l10n),
                ],
                const SizedBox(height: 24),
                _buildField(
                  label: 'الجرعة',
                  isRequired: true,
                  child: TextFormField(
                    controller: _doseController,
                    style: AppTextStyles.bodyM,
                    decoration: _buildInputDecoration(
                        context: context, hint: l10n.dosageHint),
                    onChanged: (_) => setState(() => _isDirty = true),
                    validator: (v) =>
                        v == null || v.isEmpty ? l10n.dosageRequired : null,
                  ),
                ),
                const SizedBox(height: 24),
                _buildField(
                  label: l10n.doseTimes,
                  isRequired: true,
                  child: Column(
                    children: [
                      ..._times.asMap().entries.map((entry) {
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 12),
                          child: Row(
                            children: [
                              Expanded(
                                child: InkWell(
                                  onTap: () => _selectTime(entry.key),
                                  borderRadius: BorderRadius.circular(16),
                                  child: Container(
                                    padding: const EdgeInsets.symmetric(
                                        horizontal: 16, vertical: 14),
                                    decoration: BoxDecoration(
                                      color: isDark
                                          ? AppColors.bgBaseDark
                                          : Colors.white,
                                      borderRadius: BorderRadius.circular(16),
                                      border: Border.all(
                                          color: AppColors.borderBase
                                              .withValues(alpha: 0.1)),
                                    ),
                                    child: Row(
                                      children: [
                                        Icon(Icons.access_time_filled_rounded,
                                            size: 20,
                                            color: AppColors.primary
                                                .withValues(alpha: 0.6)),
                                        const SizedBox(width: 12),
                                        Text(entry.value,
                                            style: AppTextStyles.bodyM),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              if (_times.length > 1)
                                IconButton(
                                  icon: const Icon(Icons.remove_circle_rounded,
                                      color: AppColors.textCritical),
                                  onPressed: () => _removeTime(entry.key),
                                ),
                            ],
                          ),
                        );
                      }),
                      const SizedBox(height: 4),
                      TextButton.icon(
                        onPressed: _addTime,
                        icon: const Icon(Icons.add_circle_outline_rounded),
                        label: Text(l10n.addAnotherTime),
                        style: TextButton.styleFrom(
                          foregroundColor: AppColors.primary,
                          textStyle:
                              const TextStyle(fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                _buildField(
                  label: l10n.additionalNotes,
                  child: TextFormField(
                    controller: _notesController,
                    maxLines: 3,
                    style: AppTextStyles.bodyM,
                    decoration: _buildInputDecoration(
                        context: context, hint: l10n.notesHint),
                    onChanged: (_) => setState(() => _isDirty = true),
                  ),
                ),
                const SizedBox(height: 40),
                ElevatedButton(
                  onPressed: _isSaving ? null : _save,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 18),
                    elevation: 0,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16)),
                  ),
                  child: _isSaving
                      ? const SizedBox(
                          height: 24,
                          width: 24,
                          child: CircularProgressIndicator(
                              color: Colors.white, strokeWidth: 2),
                        )
                      : Text(l10n.saveMedication,
                          style: const TextStyle(
                              fontSize: 18, fontWeight: FontWeight.bold)),
                ),
                const SizedBox(height: 32),
              ],
            ),
          ),
        ),
      ),
    );
  }

  InputDecoration _buildInputDecoration(
      {required BuildContext context,
      required String hint,
      IconData? prefixIcon}) {
    return InputDecoration(
      hintText: hint,
      hintStyle: AppTextStyles.bodyS
          .copyWith(color: AppColors.textSecondary.withValues(alpha: 0.5)),
      filled: true,
      fillColor: Theme.of(context).brightness == Brightness.dark
          ? AppColors.bgBaseDark
          : Colors.white,
      prefixIcon: prefixIcon != null
          ? Icon(prefixIcon,
              color: AppColors.textSecondary.withValues(alpha: 0.6))
          : null,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(16),
        borderSide:
            BorderSide(color: AppColors.borderBase.withValues(alpha: 0.1)),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(16),
        borderSide:
            BorderSide(color: AppColors.borderBase.withValues(alpha: 0.1)),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(16),
        borderSide: const BorderSide(color: AppColors.primary, width: 2),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(16),
        borderSide: const BorderSide(color: AppColors.textCritical, width: 1),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
    );
  }

  Widget _buildSafetyCard(AppLocalizations l10n) {
    final bool isNephrotoxic = _selectedMedData?['nephrotoxic'] ?? false;
    final bool isSafe = _selectedMedData?['safeChoice'] ?? false;
    final bool needsAdjustment = _selectedMedData?['doseAdjustment'] ?? false;
    final String? warning = l10n.localeName == 'ar'
        ? (_selectedMedData?['warning'] ?? _interactionWarning)
        : (_selectedMedData?['warningEn'] ??
            _interactionWarning); // Should add warningEn if possible

    Color color = Colors.blue;
    IconData icon = Icons.info_rounded;
    String title = l10n.drugSafetyInfo;

    if (isNephrotoxic || _interactionWarning != null) {
      color = AppColors.textCritical;
      icon = Icons.warning_rounded;
      title = _interactionWarning != null
          ? l10n.drugInteractionWarning
          : l10n.highRiskMedicationWarning;
    } else if (needsAdjustment) {
      color = AppColors.textWarning;
      icon = Icons.report_problem_rounded;
      title = l10n.adjustmentRequired;
    } else if (isSafe) {
      color = AppColors.textSuccess;
      icon = Icons.check_circle_rounded;
      title = l10n.completelySafeMedication;
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.05),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: color, size: 22),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(
                      fontWeight: FontWeight.bold, color: color, fontSize: 14),
                ),
              ),
            ],
          ),
          if (warning != null) ...[
            const SizedBox(height: 10),
            Text(
              warning,
              style: TextStyle(
                  fontSize: 13,
                  color: color.withValues(alpha: 1.0),
                  height: 1.4),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildField(
      {required String label, required Widget child, bool isRequired = false}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text(label,
                style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: Colors.grey)),
            if (isRequired)
              const Text(' *',
                  style: TextStyle(
                      color: AppColors.textCritical,
                      fontWeight: FontWeight.bold)),
          ],
        ),
        const SizedBox(height: 10),
        child,
      ],
    );
  }
}
